"""empty message

Revision ID: 14c2a3e1433d
Revises: 370cd0d27b29
Create Date: 2015-06-25 17:12:13.873525

"""

# revision identifiers, used by Alembic.
revision = '14c2a3e1433d'
down_revision = '370cd0d27b29'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('question',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_en', sa.String(length=255), nullable=True),
    sa.Column('question_es', sa.String(length=255), nullable=True),
    sa.Column('question_type', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('survey',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title_en', sa.String(length=255), nullable=True),
    sa.Column('title_es', sa.String(length=255), nullable=True),
    sa.Column('description_en', sa.String(length=255), nullable=True),
    sa.Column('description_es', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('survey_question_association',
    sa.Column('survey_id', sa.Integer(), nullable=True),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ),
    sa.ForeignKeyConstraint(['survey_id'], ['survey.id'], )
    )
    op.create_index(op.f('ix_survey_question_association_question_id'), 'survey_question_association', ['question_id'], unique=False)
    op.create_index(op.f('ix_survey_question_association_survey_id'), 'survey_question_association', ['survey_id'], unique=False)
    op.drop_table('surveys')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('surveys',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('lang', sa.VARCHAR(length=2), autoincrement=False, nullable=False),
    sa.Column('list_choice_1', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('list_choice_2', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('opinionscale_1', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('textarea_1', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('textarea_2', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('textfield_1', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('quiz_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=u'surveys_pkey')
    )
    op.drop_index(op.f('ix_survey_question_association_survey_id'), table_name='survey_question_association')
    op.drop_index(op.f('ix_survey_question_association_question_id'), table_name='survey_question_association')
    op.drop_table('survey_question_association')
    op.drop_table('survey')
    op.drop_table('question')
    ### end Alembic commands ###
