"""empty message

Revision ID: 31398dbd71bb
Revises: 4e349772aefb
Create Date: 2015-08-20 15:48:54.221021

"""

# revision identifiers, used by Alembic.
revision = '31398dbd71bb'
down_revision = '4e349772aefb'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('full_name', sa.String(length=60), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'full_name')
    ### end Alembic commands ###
