"""empty message

Revision ID: 3253d289a682
Revises: 116281055183
Create Date: 2015-07-10 10:50:29.449990

"""

# revision identifiers, used by Alembic.
revision = '3253d289a682'
down_revision = '116281055183'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
