"""empty message

Revision ID: 34d41a013f9d
Revises: 3253d289a682
Create Date: 2015-08-19 10:09:39.856006

"""

# revision identifiers, used by Alembic.
revision = '34d41a013f9d'
down_revision = '3253d289a682'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    roles = op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.bulk_insert(roles, [
        {'name': 'superadmin'},
        {'name': 'admin'}
    ])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('roles')
    ### end Alembic commands ###
