"""empty message

Revision ID: 370cd0d27b29
Revises: 51d482bf4ea1
Create Date: 2015-06-11 16:26:25.107185

"""

# revision identifiers, used by Alembic.
revision = '370cd0d27b29'
down_revision = '51d482bf4ea1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
