"""empty message

Revision ID: 380fcc2279cc
Revises: 567c3aa4112f
Create Date: 2015-06-11 11:34:10.453008

"""

# revision identifiers, used by Alembic.
revision = '380fcc2279cc'
down_revision = '567c3aa4112f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('surveys', sa.Column('lang', sa.String(length=2), nullable=False))
    op.add_column('surveys', sa.Column('list_choice_1', sa.String(length=255), nullable=True))
    op.add_column('surveys', sa.Column('list_choice_2', sa.String(length=255), nullable=True))
    op.add_column('surveys', sa.Column('opinionscale_1', sa.Integer(), nullable=True))
    op.add_column('surveys', sa.Column('textarea_1', sa.Text(), nullable=True))
    op.add_column('surveys', sa.Column('textarea_2', sa.Text(), nullable=True))
    op.add_column('surveys', sa.Column('textfield_1', sa.String(length=255), nullable=True))
    op.drop_column('surveys', 'q1')
    op.drop_column('surveys', 'survey_type')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('surveys', sa.Column('survey_type', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('surveys', sa.Column('q1', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('surveys', 'textfield_1')
    op.drop_column('surveys', 'textarea_2')
    op.drop_column('surveys', 'textarea_1')
    op.drop_column('surveys', 'opinionscale_1')
    op.drop_column('surveys', 'list_choice_2')
    op.drop_column('surveys', 'list_choice_1')
    op.drop_column('surveys', 'lang')
    ### end Alembic commands ###
