"""empty message

Revision ID: 4d97c32fac63
Revises: 4c774f8add8b
Create Date: 2015-10-30 07:41:06.822774

"""

# revision identifiers, used by Alembic.
revision = '4d97c32fac63'
down_revision = '4c774f8add8b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('monthly-report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email_list', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_monthly-report_id'), 'monthly-report', ['id'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_monthly-report_id'), table_name='monthly-report')
    op.drop_table('monthly-report')
    ### end Alembic commands ###
