"""empty message

Revision ID: 4e349772aefb
Revises: 377a4bdd4ada
Create Date: 2015-08-20 15:29:26.107497

"""

# revision identifiers, used by Alembic.
revision = '4e349772aefb'
down_revision = '377a4bdd4ada'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'first_name')
    op.drop_column('user', 'last_name')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('last_name', sa.VARCHAR(length=30), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('first_name', sa.VARCHAR(length=30), autoincrement=False, nullable=True))
    ### end Alembic commands ###
