"""empty message

Revision ID: 52be1beb7835
Revises: b99901d2c8b
Create Date: 2015-07-05 16:55:04.755946

"""

# revision identifiers, used by Alembic.
revision = '52be1beb7835'
down_revision = 'b99901d2c8b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
