"""Initial migration

Revision ID: 567c3aa4112f
Revises: None
Create Date: 2015-06-03 11:05:41.323392

"""

# revision identifiers, used by Alembic.
revision = '567c3aa4112f'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('surveys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('survey_type', sa.String(length=255), nullable=False),
    sa.Column('q1', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('surveys')
    ### end Alembic commands ###
