"""empty message

Revision ID: b99901d2c8b
Revises: 14c2a3e1433d
Create Date: 2015-07-01 19:01:27.315666

"""

# revision identifiers, used by Alembic.
revision = 'b99901d2c8b'
down_revision = '14c2a3e1433d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('survey_question_association')
    op.add_column('question', sa.Column('survey_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_question_id'), 'question', ['id'], unique=False)
    op.create_foreign_key(None, 'question', 'survey', ['survey_id'], ['id'])
    op.create_index(op.f('ix_survey_id'), 'survey', ['id'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_survey_id'), table_name='survey')
    op.drop_constraint(None, 'question', type_='foreignkey')
    op.drop_index(op.f('ix_question_id'), table_name='question')
    op.drop_column('question', 'survey_id')
    op.create_table('survey_question_association',
    sa.Column('survey_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('question_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['question_id'], [u'question.id'], name=u'survey_question_association_question_id_fkey'),
    sa.ForeignKeyConstraint(['survey_id'], [u'survey.id'], name=u'survey_question_association_survey_id_fkey')
    )
    ### end Alembic commands ###
